pub(super) mod binary_operation;
mod call;
mod detached;
mod expr_list;
mod function_declaration;
mod group;
mod if_else;
mod lambda_def;
pub(super) mod literal;
mod r#loop;
mod r#match;
mod modules;
mod range;
mod redirection;
mod r#struct;
mod substitution;
mod test;
mod r#type;
mod var_declaration;
mod var_reference;
