use analyzer::diagnostic::Diagnostic;
use analyzer::importer::ASTImporter;
use analyzer::name::Name;
use analyzer::relations::SourceId;
use analyzer::Analyzer;
use clap::Parser;
use compiler::{compile, SourceLineProvider};
use context::source::ContentId;
use dbg_pls::color;
use std::collections::HashMap;
use std::io::stderr;
use std::path::PathBuf;
use vm::{VmError, VM};

use crate::disassemble::display_bytecode;
use crate::pipeline::{ErrorReporter, FileImportError, SourceHolder};
use crate::report::{display_diagnostic, display_parse_error};

#[derive(Parser)]
#[command(author, version, about, long_about = None)]
pub struct Cli {
    /// Defines the source file to parse
    #[arg(short, long, value_name = "FILE")]
    pub(crate) source: Option<PathBuf>,

    /// Prints the generated bytecode
    #[arg(short = 'D', long)]
    pub(crate) disassemble: bool,

    /// Display a textual representation of the abstract syntax tree
    #[arg(short = 'A', long)]
    pub(crate) ast: bool,

    /// Do not execute the code
    #[arg(long = "no-execute")]
    pub(crate) no_execute: bool,
}

struct CachedSourceLocationLineProvider {
    lines: HashMap<ContentId, Vec<usize>>,
}

impl CachedSourceLocationLineProvider {
    fn compute(contents: &[ContentId], sources: &impl SourceHolder) -> Self {
        let lines = contents
            .iter()
            .map(|content_id| {
                let source = sources.get_source(*content_id).expect("unknown content id");

                let source_start_addr = source.source.as_ptr() as usize;

                let source_lines_starts: Vec<_> = source
                    .source
                    .lines()
                    .map(|line| line.as_ptr() as usize - source_start_addr)
                    .collect();

                (*content_id, source_lines_starts)
            })
            .collect();

        Self { lines }
    }
}

impl SourceLineProvider for CachedSourceLocationLineProvider {
    fn get_line(&self, content: ContentId, pos: usize) -> Option<usize> {
        self.lines.get(&content).map(|lines| {
            lines
                .binary_search(&pos)
                .map(|line| line + 1)
                .unwrap_or_else(|line| line)
        })
    }
}

pub fn use_pipeline<'a>(
    entry_point: Name,
    starting_page: SourceId,
    analyzer: &Analyzer<'a>,
    vm: &mut VM,
    diagnostics: Vec<Diagnostic>,
    importer: &mut (impl ASTImporter<'a> + ErrorReporter),
    config: &Cli,
) -> bool {
    let errors = importer.take_errors();
    if errors.is_empty() && analyzer.resolution.engine.is_empty() {
        eprintln!("No module found for entry point {entry_point}");
        return true;
    }

    let had_errors = !errors.is_empty();
    for error in errors {
        match error {
            FileImportError::IO(err) => {
                eprintln!("IO error: {err}");
            }
            FileImportError::Parse(report) => {
                for error in report.errors {
                    display_parse_error(
                        importer.get_source(report.source).unwrap(),
                        error,
                        &mut stderr(),
                    )
                    .expect("IO error when reporting diagnostics");
                }
            }
        }
    }
    if had_errors {
        return true;
    }

    if config.ast {
        for ast in analyzer
            .resolution
            .engine
            .environments()
            .filter(|(_, env)| env.parent.is_none())
            .filter_map(|(id, _)| analyzer.resolution.engine.get_expression(id))
        {
            println!("{}", color(ast))
        }
    }

    let mut stderr = stderr();
    let had_errors = !diagnostics.is_empty();
    for diagnostic in diagnostics {
        display_diagnostic(
            &analyzer.resolution.engine,
            importer,
            diagnostic,
            &mut stderr,
        )
        .expect("IO errors when reporting diagnostic");
    }

    if had_errors {
        return true;
    }
    let mut bytes = Vec::new();
    let contents = importer.list_content_ids();
    let lines = CachedSourceLocationLineProvider::compute(&contents, importer);
    compile(
        &analyzer.engine,
        &analyzer.resolution.engine,
        &analyzer.resolution.relations,
        starting_page,
        &mut bytes,
        Some(&lines),
    )
    .expect("write failed");

    if config.disassemble {
        display_bytecode(&bytes);
    }

    if !config.no_execute {
        vm.register(&bytes);
        drop(bytes);
        if unsafe { vm.run() } == Err(VmError::Internal) {
            panic!("VM internal error");
        }
    }
    had_errors
}
