name: C++ CI

on:
  push:
    paths:
      - 'vm/**'
    branches:
      - master
  pull_request:
    paths:
      - 'vm/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        compiler:
          - { c: gcc-10, cpp: g++-10 }
          - { c: gcc-12, cpp: g++-12 }
    env:
      CC: ${{ matrix.compiler.c }}
      CXX: ${{ matrix.compiler.cpp }}
    steps:
      - uses: actions/checkout@v4

      - name: Build Debug
        run: |
          cd vm
          cmake -B build -S .
          cmake --build build

      - name: Build Release
        run: |
          cd vm
          cmake -DCMAKE_BUILD_TYPE=Release -B build -S .
          cmake --build build
